version: '3'

services:
  mongodb:
    image: mongo:3.2
    command: mongod
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    volumes:
      - redis-data:/data

  elasticsearch:
    image: udata/elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  udata:
    image: udata/udata:1.5
    environment:
      - http_proxy
      - https_proxy
      - no_proxy=127.0.0.1,localhost
      - FLASK_ENV=development
    command: serve --host 0.0.0.0 --debugger --reload
    links:
      - mongodb:mongodb
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - ./udata.cfg:/udata/udata.cfg
      - .:/src/udata-koumoul
      - ../udata-data-fair:/src/udata-data-fair
      - ./static:/udata/fs
    ports:
      - "7000:7000"

volumes:
  udata-fs:
  mongo-data:
  redis-data:
  elasticsearch-data:
